name: art
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  b:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p _site && echo "<h1>OWN-ARTIFACT-REPO-B</h1>" > _site/index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
